#!/bin/sh

# symbolic-refコマンドでHEADが指しているブランチ名を取得する
branch=$(git symbolic-ref HEAD --short)

# 現在のブランチがmasterならエラー。
# 0以外のステータスを返せばpre-commitにより止まるので、エラー時に1を返す。
if [ ${branch} = master ]; then
  cat <<\EOF
  エラー：masterブランチにcommitはできません。
EOF
    exit 1
fi